cluster: "sge-submit.sh"
cluster-status: "sge-status.sh"
jobscript: "sge-jobscript.sh"
jobs: 10
default-resources: runtime=600
max-jobs-per-second: 10
max-status-checks-per-second: 10
restart-times: 2
keep-going: true
